apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/default?ref=abb200521cbc0be9559dafa635e068c8931d2406
