apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: kyverno-controller
  serviceAccountName: kustomize-controller
  path: ./config/release
  prune: true
  wait: true
  timeout: 5m
