apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../base/dev-team
patches:
  - target:
      kind: Kustomization
    patch: |
      - op: add
        path: /spec/path
        value: ./staging
