apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: flux-tenant-image-automation
  annotations:
    policy.toolkit.fluxcd.io/description: |
      Deny Flux image automation resources in tenant namespaces.
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:   ["image.toolkit.fluxcd.io"]
        apiVersions: ["*"]
        operations:  ["CREATE"]
        resources:
          - imagerepositories
          - imagepolicies
          - imageupdateautomations
  validations:
    - expression: "false"
      message: "image automation resources are not allowed in tenant namespaces"
      reason: Forbidden
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: flux-tenant-image-automation
  annotations:
    policy.toolkit.fluxcd.io/description: |
      Bind the Flux image automation restriction policy to all tenant namespaces.
spec:
  policyName: flux-tenant-image-automation
  validationActions: [Deny, Audit]
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: toolkit.fluxcd.io/tenant
          operator: Exists
