apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: apps
spec:
  serviceAccountName: dev-team
  releaseName: postgres
  chart:
    spec:
      chart: postgres
      sourceRef:
        kind: HelmRepository
        name: postgres
  interval: 5m
